version: '3.8'

services:

  client: 
    container_name: client
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - ./client:/client
      - /client/node_modules/
    depends_on: 
      - server
    ports:
      - "4000:3000"
    links:
      - server
    restart: unless-stopped

  server:
    container_name: server
    build:
      dockerfile: Dockerfile
      context: ./server
      target: development
    volumes:
      - ./server:/server
      - /server/node_modules/
    command: npm run start:debug
    depends_on:
      - db
      - db_shadow
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file: ./server/.env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SHADOW_DATABASE_URL: ${SHADOW_DATABASE_URL}


  db:
    image: mysql:8.0
    platform: linux/x86_64
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  db_shadow:
    image: mysql:8.0
    platform: linux/x86_64
    container_name: db_shadow
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data_shadow:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"

volumes:
  db_data:
  db_data_shadow: