version: '3.8'

services:

  client: 
    container_name: client
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - ./client:/client
      - /client/node_modules/
    depends_on: 
      - server
    ports:
      - 3000:3000
    links:
      - server
    restart: unless-stopped

  server:
    container_name: server
    build:
      dockerfile: Dockerfile
      context: ./server
      target: development
    env_file: ./server/.env
    volumes:
      - ./server:/server
      - /server/node_modules/
    command: npm run start:debug
    depends_on: 
      - db
    ports:
      - 4000:4000
    restart: unless-stopped

  db:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

volumes:
  db_data: